import Head from 'next/head'
// import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	const router = useRouter()
	const handleNavigation = () => {
		router.push({
			pathname: '/about',
			query: {
				aboutId: '1213',
				ref: 'hihi',
			},
		})
	}
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<button className="btn" onClick={() => handleNavigation()}>
					Click to page
				</button>
			</main>
		</>
	)
}
